resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        imageName: "ubuntu-16.04"
        conanBuildOS: "Linux"
  pool:
    vmImage: '$(imageName)'
  timeoutInMinutes: 30
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_BASE_PROFILE_OS: "Linux",
        CONAN_BASE_PROFILE_ARCH: "armv6",
        CONAN_BASE_PROFILE_COMPILER: "gcc",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "8.3",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libstdc++11",
        CONAN_BASE_PROFILE_BUILDTYPE: "Release"
      }

- job: Upload
  dependsOn:
  - Build
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://api.bintray.com/conan/tereius/public-conan",
        CONAN_LOGIN_USERNAME: "tereius",
        CONAN_PASSWORD: "$(secret)"
      }
